spring:
  config.activate.on-profile: local
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  config.activate.on-profile: test
  datasource:
    url: ${TEST_POSTGRES_URL}
    username: ${TEST_POSTGRES_USER}
    password: ${TEST_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  config.activate.on-profile: docker
  datasource:
    url: ${DOCKER_POSTGRES_URL}
    username: ${DOCKER_POSTGRES_USER}
    password: ${DOCKER_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver