services:
  product-service:
    container_name: product-service
    image: sohyun119/product-service:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        SECRET_KEY: ${SECRET_KEY}
    ports:
      - '19093:19093'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 1024mb
    cpus: 0.5
    networks:
      - limited-team25

networks:
  limited-team25:
    external: true