spring:
  application:
    name: product-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka.yml
      - classpath:properties/prometheus.yml

server:
  port: 19093