### 상품 생성
POST http://localhost:8080/api/v1/products
Content-Type: application/json
X-User-Id: 123

{
  "title": "상품7",
  "description": "상품설명",
  "price": 10000.00
}

### 상품 단건 조회
GET http://localhost:8080/api/v1/products/b373def5-9b53-42cd-ab09-b07caf26189c
Content-Type: application/json

### Internal api - 상품 단건 조회!!
GET http://localhost:8080/api/v1/internal/products/e72a45c5-c1d9-428a-9d19-813797415fb7
Content-Type: application/json

