### 상품 생성
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "title": "상품1",
  "description": "상품설명",
  "price": 10000.00
}

### 상품 단건 조회
GET http://localhost:8080/api/v1/products/fcb2d1cf-76e8-4b88-a5a4-5d76571326c5
Content-Type: application/json